# Services pour l'intégration Bidet WC

prepare_pairing:
  name: Préparer l'appairage
  description: >
    Affiche les instructions pour mettre votre bidet en mode appairage.
    Suivez ces étapes avant d'ajouter l'intégration pour faciliter la découverte de l'appareil.
  fields: {}

test_command:
  name: Tester une commande
  description: >
    Envoie une commande directe au bidet pour le débogage.
    Utilise un format binaire prédéfini ou une commande personnalisée.
  fields:
    device_id:
      name: ID de l'appareil
      description: ID de l'appareil (device_id) auquel envoyer la commande
      required: true
      example: "01234567890abcdef"
      selector:
        device:
          integration: bidet
    command_type:
      name: Type de commande
      description: Type de commande à envoyer
      required: true
      selector:
        select:
          options:
            - "flush"
            - "old_format"
            - "new_format"
            - "legacy_s0"
            - "raw"
    target_char:
      name: Caractéristique cible
      description: Choisir la caractéristique GATT d'écriture (auto, FFF1, FFE1, ou les deux)
      required: false
      default: "auto"
      selector:
        select:
          options:
            - label: "Automatique (écriture sur write_char_uuid)"
              value: "auto"
            - label: "Forcer FFF1 (0000fff1-0000-1000-8000-00805f9b34fb)"
              value: "fff1"
            - label: "Forcer FFE1 (0000ffe1-0000-1000-8000-00805f9b34fb)"
              value: "ffe1"
            - label: "Essayer FFF1 puis FFE1 (both)"
              value: "both"
    cmd:
      name: Commande (cmd) en hex
      description: Code commande (ex: 7b pour flush) utilisé par new_format/old_format
      required: false
      example: "7b"
      selector:
        text:
    value:
      name: Valeur (value) en hex
      description: Valeur associée (ex: 01 pour ON) utilisée par new_format/old_format
      required: false
      example: "01"
      selector:
        text:
    s0_type:
      name: S0 Type (hex)
      description: Type (1 octet en hex) pour legacy_s0 (format 'aaaa')
      required: false
      example: "01"
      selector:
        text:
    s0_dp:
      name: S0 DP (hex)
      description: Données DP en hex pour legacy_s0 (concaténées, sans espaces)
      required: false
      example: "0101"
      selector:
        text:
    raw_command:
      name: Commande brute (hex)
      description: Commande brute en format hexadécimal (sans espaces)
      required: false
      example: "55aa00010501010001a1"
      selector:
        text:

test_simple:
  name: Tester le bidet (simplifié)
  description: >
    Envoie une commande au premier bidet configuré sans avoir besoin de connaître l'ID de l'appareil.
    Affiche le résultat dans les notifications.
  fields:
    command_type:
      name: Type de commande
      description: Format de commande à tester
      required: false
      default: "flush"
      selector:
        select:
          options:
            - label: "Commande standard"
              value: "flush"
            - label: "Ancien format (0x55aa00010501010001a1)"
              value: "old_format"
            - label: "Nouveau format (0x55aa00060501010001db)"
              value: "new_format"

test_auth:
  name: Tester les authentifications
  description: >
    Teste différentes variantes d'authentification pour communiquer avec le bidet,
    basées sur l'analyse du code source de l'application officielle.
  fields:
    device_id:
      name: ID de l'appareil
      description: ID de l'appareil auquel envoyer la commande
      required: true
      selector:
        device:
          integration: bidet
    auth_variant:
      name: Variante d'authentification
      description: Type d'authentification à tester
      required: true
      default: "standard"
      selector:
        select:
          options:
            - label: "Standard (d8b673097b01)"
              value: "standard"
            - label: "Préfixe + commande simple (d8b6737b01)"
              value: "prefix_only"
            - label: "Préfixe inversé (27498f7b01)"
              value: "prefix_inverted"
            - label: "Format détecté dans nRF (55aa0fa10000...)"
              value: "nrf_detected"
            - label: "Auth-challenge dynamique"
              value: "challenge"
